### ISSUE TITLE
texture lose in canary while reload the page

### ISSUE THREAD

**Issue by quarksb** [webgpu/webgpu-samples#228] opened 2023-02-14 10:44 UTC
all texture related samples is effected 
such as 
[textureCube](https://austin-eng.com/webgpu-samples/samples/texturedCube)
[cubemap](https://austin-eng.com/webgpu-samples/samples/texturedCube)
may be it's a bug for canary

**Comment by austinEng** [comment] 2023-02-14 15:19
Do you have any crash report ids in about://crashes that you could share?

**Comment by quarksb** [comment] 2023-02-15 03:48
no relatiive crash is found.
can't you reproduce my issue?(texture lose when you reload page in canary)

**Comment by austinEng** [comment] 2023-02-15 19:47
Doesn't reproduce for me on Mac or Android Canary - what platform are you on?

**Comment by quarksb** [comment] 2023-02-16 02:19
![image](https://user-images.githubusercontent.com/17270069/219249352-ef18cd82-f6e2-41e2-85ec-efe1912bd108.png)
when I reload the page, the texture will disappear with a 90% probability
![image](https://user-images.githubusercontent.com/17270069/219249421-8c9aeb12-c3f5-4558-84dd-a78d7c134b59.png)
At first, I found that my [demo](https://github.com/quarksb/webgpu-image-filter) was losing textures when I refreshed the page, and I suspected that it was a problem with my code because the webgpu wasn't fully stable and maybe there was an API change that was causing the textures to be lost. But I checked your demo, and it has the same problem, so I think it's a canary problem. 
I didn't realize it was a problem with my computer ......

**Comment by austinEng** [comment] 2023-02-16 17:45
Ok. I also ran on M1 but didn't see an issue.

Could you share the contents of chrome://version/ ?
You might have a Chrome experiment that is causing the problem.

 - Are there any errors or messages in the Javascript console?
 - if you launch Chrome Canary from the command line - do you see any relevant errors or messages there?
 - if you scroll to the bottom of chrome://gpu/, do you see any relevant errors or messages?

**Comment by quarksb** [comment] 2023-02-17 07:55
thank you for your patience！
here is my contents of chorme://version
![image](https://user-images.githubusercontent.com/17270069/219584521-87423860-e5fb-4757-943a-391b378823b1.png)

- I am sure there are not any errors or messages in the Javascript console.
- I launch Chrome Canary by click the yellow canary logo, not from command line.
- when I scroll to the botton of chrome://gpu, there is nothing in log Messages
![image](https://user-images.githubusercontent.com/17270069/219583345-584a961d-6a43-4a84-a164-6d584fa0c7ec.png)

I have some more important information to give you

- this bug only appear in version 112, the stable version 110 is fine.
- it seems there are some relation between GPUcCanvasContext config alphaMode and texture lose

**Comment by austinEng** [comment] 2023-02-17 16:09
What about the "Active Variations" section of chrome://version where it shows a list of hashes?
For example, mine starts with:

```
Active Variations
cdb6e83c-ca7d8d80
df319cb2-a8e466ac
3e7d7783-377be55a
ae1f041e-377be55a
2fcbfa14-377be55a
......
```

**Comment by quarksb** [comment] 2023-02-18 01:06
here is my active Variations in chrome://version
`
2510663e-bf38427b
df319cb2-a8e466ac
3e7d7783-377be55a
2fcbfa14-377be55a
e5726113-35f09b02
c5480a51-f23d1dea
aa21b4f1-3f4a17df
9d165456-9bf9af4a
fd59f497-f23d1dea
eddd0d82-4cd6ee79
13427e22-a7aeaffe
da89714-cd57ce00
8c153587-f23d1dea
89a16501-cc8a1f04
1d167f26-3f4a17df
42f0e0ea-f51f6f50
29ea62bc-37860086
e4b818ed-3d47f4f4
9785b8cf-4711438e
87f33ad6-34f4044
6025934e-3f4a17df
4d936449-37049b31
88e143f7-ca7d8d80
250dda8b-3600185b
5be458ba-bf3103aa
1d0b1e05-fd6e8b5d
1e940a7c-3f4a17df
3458307a-abf62bce
5c2a855d-b0b34ed2
6c862974-c6af3cd9
824b2e8d-e539d649
9a24c3c2-5a4c1434
638300a1-3f4a17df
4fc3ad63-356ffe81
251b2579-2a9fe6d4
12733ec4-a77018d5
b4a41fb8-be4b462f
14246d0d-7231d8f
776f54ba-97fe4800
e521d2ef-cc8a1f04
cbc04857-3f4a17df
42f1f10d-90074468
363012bc-3f4a17df
73afac8-3f4a17df
f6f5c542-9fcd196b
7b94be1a-5419e7bd
1584cf60-3f4a17df
81b1a2c3-f23d1dea
8c82550d-377be55a
dfa02032-df3eb1c2
a582a1b8-ad75ce17
8ddeb5cd-f23d1dea
565dffc5-3f4a17df
d92d97b4-25b2f3a7
87a22c16-895c4a5b
dde50ff5-c5d8f2f6
d4f1a7b9-69d57ebb
263848e4-3f4a17df
3fd33f16-9130288a
eac1a994-3f4a17df
ae850472-e3157c71
3a4ffe07-ab2ff8bd
cb50325a-52bfb160
19d422be-eeb49769
adde0af9-c55cae7f
72fb77ee-662c9e94
6ba84beb-a22f7a04
9982045c-f23d1dea
829fa6ed-a2d707c6
f782a8be-df3eb1c2
c7c34e8b-ac8e9afa
bacf219a-cf8811b6
abaf0db8-f23d1dea
74235cf4-3f4a17df
17cd3426-f23d1dea
8659ca17-f23d1dea
910af27f-a0302284
83b371a5-3f4a17df
c44410ed-ca7d8d80
d637cfa9-377be55a
5349039a-a4655118
53c131d9-e3ef03f6
690e2db1-f23d1dea
fcb2864d-57f4d897
ed2101b4-f23d1dea
6a8d8a11-1b1cd196
75ffb03a-3f4a17df
ab1a849c-f23d1dea
b3c9749a-13e26067
25fa4483-160fcea5
da493d3c-6f028b37
f3ed486d-ca7d8d80
5c783e42-2abf9f26
bde7927d-c50d0b7f
cdf623ec-4ef08b1f
99c32967-262f0e41
4ff8f5b5-caf7a452
ad46906e-303de548
a4dcbdd6-a9152f6e
de2c80ca-f55cab5d
ca12356a-f23d1dea
741e95d4-3f4a17df
7b9d3e0c-4a0ec077
64c559ec-f23d1dea
b3f9e06f-ca7d8d80
ea23a088-d6142e30
b16eab85-f45a3452
77b7ea96-14bc7a7a
45a2f2f-c2215f84
186d6e2c-98be3e20
4ea303a6-ecbb250e
4949c1d8-c786e409
e3fd1192-f23d1dea
94edc5b9-3f4a17df
9fe21c85-377be55a
15d3083e-38ff5eda
f08c130d-3f4a17df
d5a65352-3f4a17df
c9e4cf65-4dd34122
51c78617-ca7d8d80
746780a8-c083ec6
f112d133-3f4a17df
9a564e2a-d8512bfa
b5663e5f-f23d1dea
31af02a2-ef9776e1
11b90bf1-f23d1dea
648cc0e9-ca7d8d80
8ee7d10d-3f4a17df
e80246f6-3f4a17df
371f259c-9b721d1a
9635fb98-3f4a17df
64e173c-ac6a37fc
3f2823d1-ca7d8d80
f0682056-a51a07ba
9909b8ac-f63fb7e2
e52d4c86-f23d1dea
afa71e8b-3f4a17df
5851a53a-9bf9af4a
78962b94-a79d803f
22b29f63-3f4a17df
90860314-647b8d36
7954d827-160fcea5
7ec047c2-3f4a17df
494d8760-52325d43
eadcacdf-6bdfffe7
7b2873c2-78fa69f3
3ac60855-486e2a9c
63dcb6a3-6ed79f28
e706e746-7da8925a
f296190c-b52e3392
4442aae2-a5822863
f690cf64-a90023b1
ed1d377-e1cc0f14
75f0f0a0-4ad60575
710c3f90-6bdfffe7
e2b18481-9d9eea77
e7e71889-e1cc0f14
549e50a-3f4a17df
57675af7-6ca38ae0
160d8d8d-374c34c7
4810967e-f23d1dea
1d0518a-708963b2
e135531c-3f4a17df
595f5eb0-5462ee97
bef5c006-3d47f4f4
c80a7778-43ff534b
a8cfdb40-b435379e
f9f9ca72-4b6c63cc
5f86f9e1-b435379e
dd08905f-ca7d8d80
f6e6ff36-a48e116f
42021322-bdf4a8b3
b21d000-c0581b1f
a8220f92-8e9d9a09
d954162e-edfd1b72
8d7344de-3f4a17df
10b9c277-5ec762c1
`

**Comment by austinEng** [comment] 2023-02-23 14:52
Thank you - this is the same issue as https://crbug.com/1418291 (maybe you filed it).
Seems like a browser bug; we will follow up there. I'll close this issue since it is an issue with Chrome, not with the samples.

**Closed by austinEng** 2023-02-23 14:52 UTC

**Comment by quarksb** [comment] 2023-02-24 03:12
yes, I report the issue
